import { makeItem, type Item, type Kind } from './model';
// Original, bundled SVG paths. No network fonts, remote images, or icon CDN.
export const iconPaths: Record<string, string> = {
  user: 'M8 6a4 4 0 1 0 8 0 4 4 0 1 0-8 0 M4 22v-4c0-6 16-6 16 0v4',
  decision: 'M12 2 22 12 12 22 2 12z',
  process: 'M3 5h18v14H3z M6 5v14 M18 5v14',
  terminal: 'M7 5h10a7 7 0 0 1 0 14H7A7 7 0 0 1 7 5z',
  document: 'M4 2h11l5 5v15H4z M14 2v6h6 M7 12h10 M7 16h10',
  network: 'M9 2h6v6H9z M2 16h6v6H2z M16 16h6v6h-6z M12 8v4H5v4 M12 12h7v4',
  storage: 'M3 4h18v16H3z M3 8h18 M10 12h4',
  clock: 'M12 2a10 10 0 1 0 0 20 10 10 0 1 0 0-20 M12 6v6l4 3',
  server: 'M4 3h16v7H4z M4 14h16v7H4z M7 6h1 M7 17h1 M12 6h5 M12 17h5',
  database: 'M4 6c0-4 16-4 16 0s-16 4-16 0 M4 6v12c0 4 16 4 16 0V6 M4 12c0 4 16 4 16 0',
  browser: 'M3 4h18v16H3z M3 9h18 M6 6h1 M10 6h1',
  queue: 'M3 5h18v5H3z M3 14h18v5H3z M7 7v1 M7 16v1 M11 7h6 M11 16h6',
  cloud: 'M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-1 6 6 0 0 1 0 11z',
  shield: 'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6z M8 12l3 3 5-6',
  box: 'm12 2 10 5v10l-10 5-10-5V7z M2 7l10 5 10-5 M12 12v10',
  code: 'm8 6-6 6 6 6 M16 6l6 6-6 6 M14 3l-4 18',
};
export const templates: {
  kind: Kind;
  title: string;
  subtitle: string;
  section: string;
  icon: Item['icon'];
  shape?: Item['shape'];
}[] = [
  {
    kind: 'service',
    title: 'Service',
    icon: 'server',
    subtitle: 'An independently owned capability',
    section: 'Applications',
  },
  {
    kind: 'client',
    title: 'Client',
    icon: 'browser',
    subtitle: 'Web or mobile application',
    section: 'Applications',
  },
  {
    kind: 'client',
    title: 'Person / actor',
    icon: 'user',
    subtitle: 'A user or external role',
    section: 'Applications',
  },
  {
    kind: 'service',
    title: 'API gateway',
    icon: 'network',
    subtitle: 'API routing and aggregation',
    section: 'Applications',
  },
  {
    kind: 'service',
    title: 'External system',
    icon: 'cloud',
    subtitle: 'Third-party integration',
    section: 'Applications',
  },
  {
    kind: 'service',
    title: 'Scheduled job',
    icon: 'clock',
    subtitle: 'Batch or scheduled work',
    section: 'Applications',
  },
  {
    kind: 'service',
    title: 'Function',
    icon: 'code',
    subtitle: 'Serverless or event handler',
    section: 'Applications',
  },
  {
    kind: 'database',
    title: 'Database',
    icon: 'database',
    subtitle: 'Persistent relational state',
    section: 'Data & messaging',
  },
  {
    kind: 'database',
    title: 'Cache',
    icon: 'redis',
    subtitle: 'Fast ephemeral data',
    section: 'Data & messaging',
  },
  {
    kind: 'database',
    title: 'Document store',
    icon: 'mongodb',
    subtitle: 'Document-oriented state',
    section: 'Data & messaging',
  },
  {
    kind: 'database',
    title: 'Object storage',
    icon: 'storage',
    subtitle: 'Files, media and backups',
    section: 'Data & messaging',
  },
  {
    kind: 'database',
    title: 'Search index',
    icon: 'elasticsearch',
    subtitle: 'Searchable documents',
    section: 'Data & messaging',
  },
  {
    kind: 'queue',
    title: 'Queue',
    icon: 'queue',
    subtitle: 'Asynchronous communication',
    section: 'Data & messaging',
  },
  {
    kind: 'queue',
    title: 'Event stream',
    icon: 'apachekafka',
    subtitle: 'Ordered event log',
    section: 'Data & messaging',
  },
  {
    kind: 'queue',
    title: 'Topic / pub-sub',
    icon: 'rabbitmq',
    subtitle: 'Publish and subscribe',
    section: 'Data & messaging',
  },
  {
    kind: 'container',
    title: 'Boundary',
    icon: 'box',
    subtitle: 'Nested system or domain',
    section: 'Infrastructure',
  },
  {
    kind: 'container',
    title: 'Cluster / network',
    icon: 'kubernetes',
    subtitle: 'Deployment or network boundary',
    section: 'Infrastructure',
  },
  {
    kind: 'service',
    title: 'Load balancer',
    icon: 'network',
    subtitle: 'Distribute incoming requests',
    section: 'Infrastructure',
  },
  {
    kind: 'service',
    title: 'Identity provider',
    icon: 'keycloak',
    subtitle: 'Authentication and authorization',
    section: 'Infrastructure',
  },
  {
    kind: 'service',
    title: 'Observability',
    icon: 'grafana',
    subtitle: 'Logs, metrics and traces',
    section: 'Infrastructure',
  },
  {
    kind: 'service',
    title: 'CI/CD pipeline',
    icon: 'code',
    subtitle: 'Build and delivery automation',
    section: 'Infrastructure',
  },
  {
    kind: 'service',
    title: 'CDN',
    icon: 'cloud',
    subtitle: 'Edge content delivery',
    section: 'Infrastructure',
  },
  {
    kind: 'terminal',
    title: 'Start / end',
    icon: 'terminal',
    subtitle: 'Entry or exit point',
    section: 'Flowcharts',
    shape: 'terminal',
  },
  {
    kind: 'process',
    title: 'Process',
    icon: 'process',
    subtitle: 'Action or operation',
    section: 'Flowcharts',
    shape: 'process',
  },
  {
    kind: 'decision',
    title: 'Decision',
    icon: 'decision',
    subtitle: 'Branch with labeled Yes / No connections',
    section: 'Flowcharts',
    shape: 'decision',
  },
  {
    kind: 'input',
    title: 'Input / output',
    icon: 'document',
    subtitle: 'Read or display data',
    section: 'Flowcharts',
    shape: 'input',
  },
  {
    kind: 'document',
    title: 'Document',
    icon: 'document',
    subtitle: 'Document or report',
    section: 'Flowcharts',
    shape: 'document',
  },
  {
    kind: 'process',
    title: 'Subprocess',
    icon: 'process',
    subtitle: 'Reusable process',
    section: 'Flowcharts',
    shape: 'process',
  },
  {
    kind: 'container',
    title: 'Swimlane',
    icon: 'box',
    subtitle: 'Group steps by actor or responsibility',
    section: 'Flowcharts',
  },
  {
    kind: 'participant',
    title: 'Participant / lifeline',
    icon: 'user',
    subtitle: 'Sequence diagram participant with message ports',
    section: 'Sequence diagrams',
  },
  {
    kind: 'note',
    title: 'Note',
    icon: 'code',
    subtitle: 'Decision, assumption or context',
    section: 'Annotations',
  },
];
export function libraryItem(template: (typeof templates)[number]): Item {
  const item = makeItem(template.kind);
  return {
    ...item,
    details: { ...item.details, description: template.subtitle },
    name: template.title,
    icon: template.icon,
    shape: template.shape || 'card',
    ...(template.shape === 'decision' ? { width: 240, height: 180 } : {}),
  };
}
