import {
  itemSchema,
  connectionSchema,
  validateProject,
  spaceConnectionLabels,
  type Project,
} from './model';
export function sampleProject(): Project {
  return spaceConnectionLabels(
    validateProject({
      format: 'dedalo-draw',
      version: 1,
      revision: 0,
      name: 'Commerce · system context',
      library: [],
      items: [
        itemSchema.parse({
          id: 'platform',
          kind: 'container',
          name: 'Commerce platform',
          x: 360,
          y: 100,
          width: 650,
          height: 520,
          groups: ['Commerce'],
          icon: 'box',
          details: {
            description:
              'Owns ordering and inventory. A boundary groups related capabilities; children retain their own contracts.',
          },
        }),
        itemSchema.parse({
          id: 'orders',
          parentId: 'platform',
          kind: 'service',
          name: 'Order service',
          x: 35,
          y: 90,
          groups: ['Commerce', 'Checkout'],
          icon: 'springboot',
          details: {
            description: 'Validates checkout requests and owns the order lifecycle.',
            owner: 'Commerce team',
          },
        }),
        itemSchema.parse({
          id: 'inventory',
          parentId: 'platform',
          kind: 'service',
          name: 'Inventory service',
          x: 370,
          y: 90,
          groups: ['Commerce'],
          icon: 'server',
          details: { description: 'Reserves stock with an idempotent reservation token.' },
        }),
        itemSchema.parse({
          id: 'store',
          parentId: 'platform',
          kind: 'database',
          name: 'Order database',
          x: 35,
          y: 335,
          groups: ['Commerce', 'Data'],
          icon: 'postgresql',
          details: { description: 'Stores orders and an outbox in the same transaction.' },
        }),
        itemSchema.parse({
          id: 'events',
          parentId: 'platform',
          kind: 'queue',
          name: 'Order events',
          x: 370,
          y: 335,
          groups: ['Commerce', 'Events'],
          icon: 'rabbitmq',
          details: { description: 'Durable order events for downstream consumers.' },
        }),
        itemSchema.parse({
          id: 'web',
          kind: 'client',
          name: 'Storefront',
          x: 0,
          y: 190,
          groups: ['Checkout'],
          icon: 'browser',
          details: { description: 'Collects a basket and submits checkout requests.' },
        }),
        itemSchema.parse({
          id: 'note',
          kind: 'note',
          name: 'Designed for clarity',
          x: 0,
          y: 440,
          width: 260,
          height: 155,
          icon: 'code',
          details: {
            description:
              'Click any component or connection to inspect its contract. Drag a boundary to move everything inside.',
          },
        }),
        itemSchema.parse({
          id: 'sketch',
          kind: 'stroke',
          name: 'Freehand annotation',
          x: 10,
          y: 620,
          width: 230,
          height: 20,
          points: [
            [0, 12],
            [40, 6],
            [90, 10],
            [145, 4],
            [190, 8],
            [230, 0],
          ],
          groups: ['Annotations'],
        }),
      ],
      connections: [
        connectionSchema.parse({
          id: 'checkout',
          direction: 'bidirectional',
          color: 'blue',
          source: 'web',
          target: 'orders',
          name: 'Submit order',
          groups: ['Checkout'],
          details: {
            protocol: 'HTTPS',
            encoding: 'JSON',
            request: 'POST /orders · basketId, customerId, idempotencyKey',
            response: '201 Created · orderId, status, total',
            failure: '409 stock conflict; retry only with the same idempotency key.',
            timeout: '3 seconds; one bounded retry',
            security: 'OAuth 2 bearer token',
            description: 'Creates one order for a validated basket.',
          },
        }),
        connectionSchema.parse({
          id: 'reserve',
          direction: 'bidirectional',
          color: 'blue',
          source: 'orders',
          target: 'inventory',
          name: 'Reserve stock',
          details: {
            protocol: 'gRPC',
            encoding: 'Protobuf',
            request: 'ReserveStock(orderId, lines[])',
            response: 'Reservation(token, expiresAt)',
            failure:
              'Insufficient stock is a domain response; DEADLINE_EXCEEDED requires reconciliation.',
            timeout: '800 milliseconds',
            description: 'Reserves all requested lines atomically.',
          },
        }),
        connectionSchema.parse({
          id: 'persist',
          direction: 'bidirectional',
          color: 'blue',
          source: 'orders',
          target: 'store',
          name: 'Persist order',
          groups: ['Data'],
          details: {
            protocol: 'PostgreSQL wire protocol',
            request: 'Insert order + outbox event in one transaction',
            response: 'Committed order ID',
            failure: 'Roll back both writes',
            description: 'Transactional persistence.',
          },
        }),
        connectionSchema.parse({
          id: 'publish',
          direction: 'one-way',
          color: 'warning',
          source: 'store',
          target: 'events',
          name: 'Publish event',
          groups: ['Events'],
          details: {
            protocol: 'AMQP',
            encoding: 'JSON',
            request: 'OrderCreated v1',
            failure: 'Retry with deduplication by eventId',
            description: 'An outbox relay publishes committed events.',
          },
        }),
      ],
    }),
  );
}
